# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cb6c0217908a09bc10c64d64a715ebf6419fea729ff81b89f2944efef0b55646f8bc62f2239b8c0f925d0104664659fff7c193655d7bb1fa788782e91a11390

test:
  secret_key_base: 4ec03d0ea557f5ec8c6baeeeb85411c4ab4e5416ac30cfce854e7a8665f2b28a39d646b3907269b6099c0a38f3067662ec9d02c65a6eaf649d79312f4917a3b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
